### ISSUE TITLE
wireless connection

### ISSUE THREAD

**Issue by belagio** [mjs513/FreeIMU-Updates#65]
Hi
I want to use freeimu with wireless connection. I have HM-TRP modules for wireless connection. After I assemble this module to free imu and test it the processing shows zero.
Please help me how can I make freeimu with wireless connection.
Thank you.

**Comment by mjs513** [comment]
It looks like the module you are using requires a separate arduino library.
Also since I do not have these modules and I don't know what is required on
pc side with processing to implement correctly.  Right now I am only
supporting xbee since that is the most common.  Sorry I couldn't be of more
help.

**Comment by belagio** [comment]
Thank you
If I want to use xbee, what kind of this I can use?
If I want to use xbee, I should use freeimu serial for arduino and freeimu cube xbee for processing.
Thank you

**Comment by belagio** [comment]
Hello MJ
Thank you for helping me.
Bye
