### ISSUE TITLE
ESP32 - MPU9250: fatal error: ADXL345.h: No such file or directory

### ISSUE THREAD

**Issue by sdaxini** [mjs513/FreeIMU-Updates#89]
I have tried to manually import the libraries into the Arduino library folder as well as Add .Zip library and also tried to move the adxl345driver and other folders under FreeIMU\libraries to one level up but for some reason my compile always fails stating that the ADXL345.h is missing. I am on Arduini 1.8.2 and followed all the instructions in Instructions.txt for the #defines and other settings but cant seem to get the libraries imported correctly no matter what I try. Any help appreciated.

After I have copied the FreeIMU files to the Arduino libraries folder, if I go to Sketch - Include Library - Manage Libraries... I see the following error...

Invalid library found in C:\Users\blah\Documents\Arduino\libraries\FreeIMU: C:\Users\blah\Documents\Arduino\libraries\FreeIMU

Thanks,
-Shail

**Comment by mjs513** [comment]
All libraries should be put in your local Arduino folder, so it should look like this, which for you should be, C:\Users\blah\Documents\Arduino\libraries :

![image](https://user-images.githubusercontent.com/5366213/29323430-e21a8ec4-81ae-11e7-92be-5a3e7aa20410.png)

if I go to manage libraries I see this:
![image](https://user-images.githubusercontent.com/5366213/29323580-5bd08fa2-81af-11e7-8aa7-77779716799e.png)
and
![image](https://user-images.githubusercontent.com/5366213/29323607-707ac918-81af-11e7-987c-cfbb9a3314b2.png)

With that said you could just try deleting that include since you are not using it for the MPU9250
